---
title: "LSO-dfbeta"
author: "Kevin O'Brien"
date: "Wednesday, August 05, 2015"
output: html_document
---

```{r}
#using package NLME
library(nlme)
source("data/BloodData.R")
```
### Working on the JS comparison
```{r}
blood = groupedData( BP ~ method | subject ,
  data = data.frame( BP = c(Blood), 
    subject = rep(seq(nrow(Blood)), ncol(Blood)),
  	method = rep(c("J","R","S"), rep(nrow(Blood)*3, 3)),
		repl = rep(rep(c(1:3), rep(nrow(Blood), 3)), 3) ),
	labels = list(BP = "Systolic Blood Pressure", method = "Measurement Device"),
	)
```

```{r}
# consider on methods "J" and "S"
dat = subset(blood, subset = method != "R") # fixed-effects X_i with(subset(dat, subset = subject == "1"), model.matrix(BP ~ method)) # random-effects Z_i with(subset(dat, subset = subject == "1"), model.matrix( ~ method -1))


# consider J and S groups only:
# J.sd = c(with(subset(blood, subset = method == "J"), by(BP, subject, sd))) 
# S.sd = c(with(subset(blood, subset = method == "S"), by(BP, subject, sd)))
# min(J.sd) ; max(J.sd)
# min(S.sd) ; max(S.sd)
# plot(J.sd, S.sd)
```

```{r}
# make a data frame containing J and S groups only:
dat = subset(blood, subset = method != "R")

```


```{r}
JS.roy1 = lme(BP ~ method-1, data = dat,random = list(subject=pdSymm(~ method-1)), weights=varIdent(form=~1|method),correlation = corSymm(form=~1 | subject/repl), method="ML")


```

```{r}

all.res1=numeric(nrow(dat))
all.res2=numeric(nrow(dat))
```
```{r}
for(i in 1:length(subject)){
  LSOmodel = lme(BP ~ method-1, 
                 data = dat[dat$subject != i,],
                 random = list(subject=pdSymm(~ method-1)), 
                 weights=varIdent(form=~1|method),
                 correlation = corSymm(form=~1 | subject/repl), 
                 method="ML")

  all.res1[i]=fixef(LSOmodel)[1]
  all.res2[i]=fixef(LSOmodel)[2]

}
```